[build]
builder = "NIXPACKS"
buildCommand = "npm install && npm run build"
startCommand = "node .output/server/index.mjs"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"