/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as EmergencyRouteImport } from './routes/emergency'
import { Route as FindRouteImport } from './routes/find'
import { Route as ForVetsRouteImport } from './routes/for-vets'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedVetConsoleRouteImport } from './routes/_authenticated/vet-console'
import { Route as BookVetIdRouteImport } from './routes/book.$vetId'
import { Route as VetsVetIdRouteImport } from './routes/vets.$vetId'
import { Route as AuthenticatedAdminVerificationsRouteImport } from './routes/_authenticated/admin.verifications'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyRoute = EmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => rootRouteImport,
} as any)
const FindRoute = FindRouteImport.update({
  id: '/find',
  path: '/find',
  getParentRoute: () => rootRouteImport,
} as any)
const ForVetsRoute = ForVetsRouteImport.update({
  id: '/for-vets',
  path: '/for-vets',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVetConsoleRoute = AuthenticatedVetConsoleRouteImport.update({
  id: '/vet-console',
  path: '/vet-console',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const BookVetIdRoute = BookVetIdRouteImport.update({
  id: '/book/$vetId',
  path: '/book/$vetId',
  getParentRoute: () => rootRouteImport,
} as any)
const VetsVetIdRoute = VetsVetIdRouteImport.update({
  id: '/vets/$vetId',
  path: '/vets/$vetId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminVerificationsRoute =
  AuthenticatedAdminVerificationsRouteImport.update({
    id: '/admin/verifications',
    path: '/admin/verifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/emergency': typeof EmergencyRoute
  '/find': typeof FindRoute
  '/for-vets': typeof ForVetsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/vet-console': typeof AuthenticatedVetConsoleRoute
  '/book/$vetId': typeof BookVetIdRoute
  '/vets/$vetId': typeof VetsVetIdRoute
  '/admin/verifications': typeof AuthenticatedAdminVerificationsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/emergency': typeof EmergencyRoute
  '/find': typeof FindRoute
  '/for-vets': typeof ForVetsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/vet-console': typeof AuthenticatedVetConsoleRoute
  '/book/$vetId': typeof BookVetIdRoute
  '/vets/$vetId': typeof VetsVetIdRoute
  '/admin/verifications': typeof AuthenticatedAdminVerificationsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/emergency': typeof EmergencyRoute
  '/find': typeof FindRoute
  '/for-vets': typeof ForVetsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/vet-console': typeof AuthenticatedVetConsoleRoute
  '/book/$vetId': typeof BookVetIdRoute
  '/vets/$vetId': typeof VetsVetIdRoute
  '/_authenticated/admin/verifications': typeof AuthenticatedAdminVerificationsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistant'
    | '/auth'
    | '/emergency'
    | '/find'
    | '/for-vets'
    | '/dashboard'
    | '/vet-console'
    | '/book/$vetId'
    | '/vets/$vetId'
    | '/admin/verifications'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistant'
    | '/auth'
    | '/emergency'
    | '/find'
    | '/for-vets'
    | '/dashboard'
    | '/vet-console'
    | '/book/$vetId'
    | '/vets/$vetId'
    | '/admin/verifications'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/assistant'
    | '/auth'
    | '/emergency'
    | '/find'
    | '/for-vets'
    | '/_authenticated/dashboard'
    | '/_authenticated/vet-console'
    | '/book/$vetId'
    | '/vets/$vetId'
    | '/_authenticated/admin/verifications'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AssistantRoute: typeof AssistantRoute
  AuthRoute: typeof AuthRoute
  EmergencyRoute: typeof EmergencyRoute
  FindRoute: typeof FindRoute
  ForVetsRoute: typeof ForVetsRoute
  BookVetIdRoute: typeof BookVetIdRoute
  VetsVetIdRoute: typeof VetsVetIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency': {
      id: '/emergency'
      path: '/emergency'
      fullPath: '/emergency'
      preLoaderRoute: typeof EmergencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find': {
      id: '/find'
      path: '/find'
      fullPath: '/find'
      preLoaderRoute: typeof FindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-vets': {
      id: '/for-vets'
      path: '/for-vets'
      fullPath: '/for-vets'
      preLoaderRoute: typeof ForVetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vet-console': {
      id: '/_authenticated/vet-console'
      path: '/vet-console'
      fullPath: '/vet-console'
      preLoaderRoute: typeof AuthenticatedVetConsoleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/book/$vetId': {
      id: '/book/$vetId'
      path: '/book/$vetId'
      fullPath: '/book/$vetId'
      preLoaderRoute: typeof BookVetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vets/$vetId': {
      id: '/vets/$vetId'
      path: '/vets/$vetId'
      fullPath: '/vets/$vetId'
      preLoaderRoute: typeof VetsVetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/verifications': {
      id: '/_authenticated/admin/verifications'
      path: '/admin/verifications'
      fullPath: '/admin/verifications'
      preLoaderRoute: typeof AuthenticatedAdminVerificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedVetConsoleRoute: typeof AuthenticatedVetConsoleRoute
  AuthenticatedAdminVerificationsRoute: typeof AuthenticatedAdminVerificationsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedVetConsoleRoute: AuthenticatedVetConsoleRoute,
  AuthenticatedAdminVerificationsRoute: AuthenticatedAdminVerificationsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AssistantRoute: AssistantRoute,
  AuthRoute: AuthRoute,
  EmergencyRoute: EmergencyRoute,
  FindRoute: FindRoute,
  ForVetsRoute: ForVetsRoute,
  BookVetIdRoute: BookVetIdRoute,
  VetsVetIdRoute: VetsVetIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
